(function () {
  // Legacy message-board archive on the guestbook page.
  //
  // The page body (generated by tools/migrate.py) ships the card markup plus a
  // JSON copy table in `data-guestbook-copy`; the entries themselves come from
  // the blog API (/api/guestbook/list), cursor-paged through the "load more"
  // button. Everything the API returns is visitor-written, so every field is
  // escaped before it is interpolated into innerHTML.
  function initGuestbook() {
    var root = document.querySelector('[data-guestbook-root]');
    if (!root) return;

    var copy;
    try {
      copy = JSON.parse(root.getAttribute('data-guestbook-copy') || '{}');
    } catch (error) {
      copy = {};
    }
    if (!copy || typeof copy !== 'object') copy = {};

    var list = root.querySelector('[data-guestbook-list]');
    var status = root.querySelector('[data-guestbook-status]');
    var more = root.querySelector('[data-guestbook-more]');
    var entriesApi = (window.__AKARI_API_BASE__ || '/api') + '/guestbook/list';
    var nextCursor = null;
    var loading = false;

    function escapeHtml(value) {
      return String(value == null ? '' : value).replace(/[&<>"']/g, function (char) {
        return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char];
      });
    }

    function setStatus(message, kind) {
      if (!status) return;
      status.textContent = message || '';
      status.hidden = !message;
      status.setAttribute('data-kind', kind || '');
    }

    function formatDate(value) {
      var date = new Date(value);
      // Invalid dates (and old engines that reject the options object) fall
      // back to a plain ISO slice rather than an "Invalid Date" string.
      if (!isFinite(date.getTime())) return '';
      try {
        return date.toLocaleString(document.documentElement.lang || 'en', {
          dateStyle: 'medium',
          timeStyle: 'short'
        });
      } catch (error) {
        return date.toISOString().slice(0, 16).replace('T', ' ');
      }
    }

    function buildEntry(entry) {
      var avatar = escapeHtml(entry.avatarUrl || entry.fallbackAvatarUrl || '');
      var fallback = escapeHtml(entry.fallbackAvatarUrl || '');
      var nickname = escapeHtml(entry.nickname || 'Guest');
      var content = escapeHtml(entry.content || '').replace(/\n/g, '<br>');
      var createdAt = escapeHtml(formatDate(entry.createdAt));
      return (
        '<article class="guestbook-entry">' +
        '<img class="guestbook-entry__avatar" src="' + avatar + '" alt="" loading="lazy" decoding="async" referrerpolicy="no-referrer" onerror="this.onerror=null;this.src=\'' + fallback + '\'">' +
        '<div class="guestbook-entry__body"><header><strong>' + nickname + '</strong><time>' + createdAt + '</time></header><p>' + content + '</p></div>' +
        '</article>'
      );
    }

    function renderEntries(entries, append) {
      if (!list) return;
      var html = (entries || []).map(buildEntry).join('');
      if (append) list.innerHTML += html;
      else list.innerHTML = html;
    }

    function loadEntries(append) {
      if (loading) return;
      loading = true;
      if (!append) setStatus(copy.loading || 'Loading…');

      var url = entriesApi + (append && nextCursor ? '?cursor=' + encodeURIComponent(nextCursor) : '');
      fetch(url, { credentials: 'omit' })
        .then(function (response) {
          if (!response.ok) throw new Error('HTTP ' + response.status);
          return response.json();
        })
        .then(function (data) {
          var entries = Array.isArray(data.entries) ? data.entries : [];
          renderEntries(entries, append);
          nextCursor = data.nextCursor || null;
          if (more) more.hidden = !nextCursor;
          if (!append && !entries.length) setStatus(copy.empty || 'No messages yet.');
          else setStatus('');
        })
        .catch(function () {
          setStatus(copy.errorServer || 'Failed to load.', 'error');
        })
        .then(function () {
          loading = false;
        }, function () {
          loading = false;
        });
    }

    if (more) more.addEventListener('click', function () { loadEntries(true); });

    loadEntries(false);
  }

  // The script is deferred, so the document is usually parsed already; the
  // listener covers the synchronous case (e.g. injected after load).
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initGuestbook, { once: true });
  } else {
    initGuestbook();
  }
})();
